### PR TITLE
Basic Refactoring

### PR DESCRIPTION
**Pull request by sahil-shubham**

### CODE REVIEW

**Comment by sahil-shubham** [comment]
@chirag828049 Can you move script files inside `backend/` to `backend/scripts/` whenever you have nothing to do.

**Comment by chirag828049** [comment]
There are 2 scripts which run daily via cronjob. we have to change the commands in https://github.com/project-ias/project-ias/blob/70f671be2efdce5fc857bba4466161092dc16572/backend/apis/run_cronjob.js

**Comment by sahil-shubham** [comment]
Alright, let's move the files ran by the shell scripts in scripts folder too. No need to have all these "add__to__" files outside. 
image

**Comment by chirag828049** [comment]
Yeah that would be a lot better.

**Review by sahil-shubham — COMMENTED** [review]
Let's merge this, most of the changes are mostly linting based. Refactoring is turning badly written code to something that looks good while working, which we didn't do in this pull request.

**Comment by chirag828049** [comment]
closes #30

**Pull request merged**
